spring.application.name=restaurant-reservations

# MySQL Database
spring.datasource.url=jdbc:mysql://hayabusa.proxy.rlwy.net:57192/railway
spring.datasource.username=root
spring.datasource.password=wXmkSFRcNsLMTMtENheKMOHTSQjNacCY

# JPA
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Puerto
server.port=8080